---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-4
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://192.168.1.20:9000 # 
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - /home/andrei/data/mealie:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-4
    container_name: mealie-api
    volumes:
      - /home/andrei/data/mealie:/app/data/
    ports:
      - "9000:9000"
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://192.168.1.20
      - HOST=0.0.0.0
      - DEFAULT_EMAIL=candale.andrei@gmail.com
    restart: always

