#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

(crontab -l; echo "0 1 * * */3 ~/workspace/backup/run_backup backup") | crontab -
